### ISSUE TITLE
咋还用yolov4

### ISSUE THREAD

**Issue by lengsan1234** [gemingjia/obstacles_to_identify#2]

**Comment by lengsan1234** [comment]
请问可以替换吗

**Comment by gmjneko** [comment]
很久很久前做的项目了，代码质量也不高，如需要新版的话可以看看其他的通用识别的开源项目，测距之类的我都写了详细的注释，可以作为参考。

**Comment by lengsan1234** [comment]
好的请问有成品吗

**Comment by gmjneko** [comment]
> 好的请问有成品吗

新版的成品我这里没有，很久没做这方面了。我这个的话本身就是成品了，直接拿来用就可以的。
